services:
  postgres:
    image: postgres:17
    container_name: ai-career-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome2ibm
      POSTGRES_DB: careercopilot
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: